/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import Modelo.Producto;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import persistencia.ControladoraProducto;

/**
 *
 * @author marco
 */
public class VentanaRestaurarProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRestaurarProductos.class.getName());

     private JTable tablaInactivos;
    private JButton btnRestaurar;
    private DefaultTableModel modelo;
    private ControladoraProducto control;

    public VentanaRestaurarProductos() {
        setTitle("Productos Inactivos (Papelera)");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(600, 400);
        setLocationRelativeTo(null);

        control = new ControladoraProducto();

        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Código", "Nombre", "Rubro", "Unidad", "Precio", "Cantidad"});

        tablaInactivos = new JTable(modelo);
        JScrollPane scrollPane = new JScrollPane(tablaInactivos);

        btnRestaurar = new JButton("Restaurar Producto");
        btnRestaurar.addActionListener(e -> restaurarSeleccionado());

        add(scrollPane, java.awt.BorderLayout.CENTER);
        add(btnRestaurar, java.awt.BorderLayout.SOUTH);

        cargarProductosInactivos();
    }

    private void cargarProductosInactivos() {
        modelo.setRowCount(0);
        List<Producto> productos = control.obtenerProductosInactivos();
        for (Producto p : productos) {
            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getNombre(),
                p.getRubro(),
                p.getUnidad(),
                p.getPrecio(),
                p.getCantidad()
            });
        }
    }

    private void restaurarSeleccionado() {
        int fila = tablaInactivos.getSelectedRow();
        if (fila >= 0) {
            int codigo = Integer.parseInt(tablaInactivos.getValueAt(fila, 0).toString());
            control.restaurarProducto(codigo);
            cargarProductosInactivos();
            JOptionPane.showMessageDialog(this, "Producto restaurado correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para restaurar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaRestaurarProductos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
